# Generated by Django 4.2.27 on 2026-01-13 19:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_post_dislikes_post_likes'),
    ]

    operations = [
    ]
